### ISSUE TITLE
Enhancement(animation for already drew line)

### ISSUE THREAD

**Issue by Mohd-ajmal** [moxiaov587/slidable_line_chart#16]
I am reaching out to kindly request assistance with creating an animation. Specifically, I am seeking an animation where a line gradually disappears from the beginning to the end as it touches the right side. Would it be possible for you to assist me with this task? Your expertise in this matter would be greatly appreciated.

**Comment by moxiaov587** [comment]
https://github.com/moxiaov587/slidable_line_chart/assets/46736634/8de217be-95d5-4f32-b473-88ad9e3fbd7b

Is this what you want? Then I want to know what situation you need this animation for, is it also ECG, if possible please give me a minimal use case and let me see how you use it, because the functionality of this package is actually for sliding some A simple line chart is used to complete the interaction.

**Comment by Mohd-ajmal** [comment]
https://github.com/moxiaov587/slidable_line_chart/assets/90542307/7c238643-26e5-449c-a476-5dd697193553

I'm currently using this package for real-time plotting of ECG data, and I need to create a gap between the lines to resemble a hospital ECG graph. To achieve this, I'm planning to implement a reverse animation. Once the first line completes, I'll reverse it and then push the second line with new data, adding a few milliseconds delay. This approach will help me create the desired gap between lines. Could you please provide guidance on how to implement this, similar to the previous video you shared? Your assistance would be greatly appreciated. Thank you!

**Comment by Mohd-ajmal** [comment]
Hi @moxiaov587, can you please tell me, how you did it because which is very very important in our project if you want more details means please let me know.

**Comment by moxiaov587** [comment]
Sorry, I have been busy at work recently. I was thinking that the ECG you want should not use this package. I used my spare time to create the above effect, but as you can see, there are still many problems. I will continue to try. It should appear as a new package as it is completed, but I can't guarantee when it will be completed.

https://github.com/moxiaov587/slidable_line_chart/assets/46736634/d9c96479-a868-445e-ab50-cfc82cb92ce3

Or do you just want an animation like the one above? Then I can make a method for you to use.

**Comment by Mohd-ajmal** [comment]
One more thing, if you suggest some idea about real time ecg plot, that should help me a lot, like other than this how we can achieve similar to [this](https://github.com/moxiaov587/slidable_line_chart/issues/16#issuecomment-2035882898) is there any efficient way to do this?

**Comment by Mohd-ajmal** [comment]
Hi @moxiaov587, can you please provide [this](https://github.com/moxiaov587/slidable_line_chart/issues/16#issuecomment-2029060127) function. if you have time please.

**Comment by moxiaov587** [comment]
You can import it with

```yaml
slidable_line_chart:
    git:
      url: https://github.com/moxiaov587/slidable_line_chart.git
      ref: a80d4fe
```
This is [example](https://github.com/moxiaov587/slidable_line_chart/blob/a80d4fe4771f44eefcfbddedec60ad6ccd34afd6/example/lib/full_feat_example.dart#L340-L356).

If you have no further questions I will release a new version.

**Comment by Mohd-ajmal** [comment]
Thanks a lot, for your meaningful time.
